import { jsPDF } from "jspdf";

export default function generatePdf(scan) {
  const doc = new jsPDF();

  const analysis = scan.analysis || {};

  // ======================================
  // PAGE BORDER
  // ======================================

  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(1.2);
  doc.rect(8, 8, 194, 281);

  // ======================================
  // HEADER
  // ======================================

  doc.setFillColor(15, 23, 42);

  doc.rect(
    8,
    8,
    194,
    28,
    "F"
  );

  doc.setTextColor(
    255,
    255,
    255
  );

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(24);

  doc.text(
    "MEDILENS AI",
    20,
    25
  );

  doc.setFontSize(10);

  doc.text(
    "AI-Powered Medicine Analysis Report",
    112,
    25
  );

  doc.setTextColor(
    0,
    0,
    0
  );

  let y = 50;

  // ======================================
  // REPORT DETAILS
  // ======================================

  doc.setFontSize(11);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    y
  );

  doc.text(
    `Report ID: ML-${Date.now()}`,
    120,
    y
  );

  y += 15;

  // ======================================
  // MEDICINE BOX
  // ======================================

  doc.roundedRect(
    15,
    y,
    180,
    28,
    3,
    3
  );

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(16);

  doc.text(
    analysis.medicine_name ||
      "Unknown Medicine",
    20,
    y + 10
  );

  doc.setFont(
    "helvetica",
    "normal"
  );

  doc.setFontSize(10);

  doc.text(
    `Scan Date: ${
      scan.scannedAt || "Unknown"
    }`,
    20,
    y + 20
  );

  y += 45;

  // ======================================
  // SECTION HELPER
  // ======================================

  const addSection = (
    title,
    content
  ) => {

    if (y > 245) {
      doc.addPage();

      doc.setDrawColor(
        15,
        23,
        42
      );

      doc.setLineWidth(1.2);

      doc.rect(
        8,
        8,
        194,
        281
      );

      y = 20;
    }

    doc.setFillColor(
      219,
      234,
      254
    );

    doc.rect(
      15,
      y - 5,
      180,
      10,
      "F"
    );

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.setFontSize(13);

    doc.text(
      title,
      20,
      y + 2
    );

    y += 14;

    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.setFontSize(11);

    const lines =
      doc.splitTextToSize(
        content ||
          "Not available",
        170
      );

    doc.text(
      lines,
      20,
      y
    );

    y +=
      lines.length * 6 +
      12;
  };

  // ======================================
  // MAIN REPORT
  // ======================================

  addSection(
    "AI SUMMARY",
    analysis.ai_summary
  );

  addSection(
    "WHAT THIS MEDICINE DOES",
    analysis.what_it_does
  );

  addSection(
    "HOW TO TAKE THIS MEDICINE",
    analysis.how_to_take
  );

  addSection(
    "STORAGE INSTRUCTIONS",
    analysis.storage
  );

  addSection(
    "WHO SHOULD BE CAREFUL",
    (
      analysis.who_should_be_careful ||
      []
    )
      .map(
        (item) =>
          `• ${item}`
      )
      .join("\n")
  );

  addSection(
    "SEEK MEDICAL HELP IF",
    (
      analysis.seek_medical_help_if ||
      []
    )
      .map(
        (item) =>
          `• ${item}`
      )
      .join("\n")
  );

  addSection(
    "POSSIBLE SIDE EFFECTS",
    (
      analysis.side_effects ||
      []
    )
      .map(
        (item) =>
          `• ${item}`
      )
      .join("\n")
  );

  addSection(
    "IMPORTANT WARNINGS",
    (
      analysis.important_warnings ||
      []
    )
      .map(
        (item) =>
          `• ${item}`
      )
      .join("\n")
  );

  // ======================================
  // INGREDIENTS
  // ======================================

  const ingredientsText =
    (
      analysis.ingredients ||
      []
    )
      .map(
        (ingredient) =>
          `${ingredient.name}\n${ingredient.purpose}`
      )
      .join("\n\n");

  addSection(
    "ACTIVE INGREDIENTS",
    ingredientsText ||
      "Not available"
  );

  // ======================================
  // SIGNATURE
  // ======================================

  if (y > 220) {
    doc.addPage();

    doc.setDrawColor(
      15,
      23,
      42
    );

    doc.setLineWidth(1.2);

    doc.rect(
      8,
      8,
      194,
      281
    );

    y = 40;
  }

  y += 20;

  doc.line(
    120,
    y,
    180,
    y
  );

  doc.setFontSize(10);

  doc.text(
    "Generated By",
    120,
    y + 8
  );

  doc.text(
    "MediLens AI",
    120,
    y + 14
  );

  doc.text(
    "Anthriksh",
    120,
    y + 20
  );

  // ======================================
  // FOOTER
  // ======================================

  const footerY = 270;

  doc.setFontSize(8);

  doc.setTextColor(
    90
  );

  doc.line(
    20,
    footerY - 5,
    190,
    footerY - 5
  );

  doc.text(
    "MediLens AI • AI-Powered Medicine Intelligence Platform",
    20,
    footerY
  );

  doc.text(
    "Developed by Anthriksh | AI & Machine Learning Engineer",
    20,
    footerY + 5
  );

  doc.text(
    "This report is generated using OCR and AI analysis. Always consult a qualified healthcare professional before making medical decisions.",
    20,
    footerY + 10,
    {
      maxWidth: 170,
    }
  );

  // ======================================
  // SAVE PDF
  // ======================================

  doc.save(
    `${
      analysis.medicine_name ||
      "Medicine_Report"
    }.pdf`
  );
}